### ISSUE TITLE
ReCaptcha Support für Burning Series

### ISSUE THREAD

**Issue by John-Kodi** [lastship/plugin.video.xstream#31]
Ist es möglich, eine ReCaptcha Abfrage für Burning Series einzubauen, wenn der Link eines Streams durch eben diese blockiert wird? Vielleicht kann die Funktion aus dem URLResolver verwendet werden: 

https://github.com/tvaddonsco/script.module.urlresolver/blob/master/lib/urlresolver/plugins/lib/recaptcha_v2.py

**Comment by sraedler** [comment]
Das arbeitet mit dem Fallback von recaptcha2.

Das ist nicht mehr unterstützt.

siehe https://developers.google.com/recaptcha/docs/faq
