### ISSUE TITLE
Geht nicht mehr richtig

### ISSUE THREAD

**Issue by Maxxxel** [lastship/plugin.video.xstream#42]
Seit heute findet er über die globale Suche fast nichts mehr. Und Moviestreams.to funzt sowieso nicht, immer die selben hoster die niemals funktionieren

**Comment by anis3** [comment]
@Maxxxel 
das liegt an cloudflare hoffe das es jetzt behoben ist
aber die seite von dir geschrieben "Moviestreams.to"
kenne ich nicht ist/war auch nicht in xStream
meinst du "movie-stream.eu" kann ich nicht bestätigen das
die seite aktuell nicht funktioniert
LG Anis
